from TikTokApi import TikTokApi
from datetime import datetime

class TkTkUser:

    def __init__(self, username, custom_verifyFp):
        self.username = username
        self.custom_vefifyFp = custom_verifyFp
        self.api = TikTokApi.get_instance(custom_verifyFp=custom_verifyFp,
                                          use_selenium=True,
                                          use_test_endpoint=True)
        # custom_verifyFp is the string generated by browser and verify the identity of the browser

        data = self.api.get_user(username=username)
        self.json_data = data

        self.id_ = data['userInfo']['user']['id']
        # self.username = data['userInfo']['user']['uniqueId']
        self.nickname = data['userInfo']['user']['nickname']
        self.is_private = data['userInfo']['user']['privateAccount']
        self.is_verified = data['userInfo']['user']['verified']
        self.followerCount = data['userInfo']['stats']['followerCount']
        self.followingCount = data['userInfo']['stats']['followingCount']
        self.heartCount = data['userInfo']['stats']['heartCount']
        self.videoCount = data['userInfo']['stats']['videoCount']
        self.created_at = datetime.strftime(datetime.fromtimestamp(data['userInfo']['user']['createTime']), '%Y-%m-%d')
        for i in data['seoProps']['jsonldList']:
            if i[0] == 'Person':
                self.description = i[1]['description']
