# Generated by Django 3.1 on 2020-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="readers",
            fields=[
                ("email", models.TextField(primary_key=True, serialize=False)),
                ("password", models.TextField()),
            ],
        ),
    ]
