name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is labelled as stale because it has been open for more than 7 days with no activity.'
        days-before-stale: 7
        days-before-close: 7
        stale-issue-label: 'stale'
        exempt-issue-labels: 'Announcement,Pinned'
        remove-stale-when-updated: true
